### ISSUE TITLE
Upload build artifacts for Python 3.8 to pypi.org

### ISSUE THREAD

**Issue by ecederstrand** [InsightSoftwareConsortium/ITKMeshToPolyData#23]
The list of download files at https://pypi.org/project/itk-meshtopolydata/#files is missing cp38 files, and there is no source package.

Can you please build and upload files for this version, or release a new version that can be installed on Python 3.8?

```bash
$ python --version
Python 3.8.1
$ python -m pip install itk-meshtopolydata
ERROR: Could not find a version that satisfies the requirement itk-meshtopolydata
ERROR: No matching distribution found for itk-meshtopolydata
```

**Comment by thewtex** [comment]
Yes, this is planned after the ITK 5.1.0 final release.

**Comment by Stewart18** [comment]
I'm trying to install itkwidgets, and it seems to be dependent on itk having itk-meshtopolydata. How can I install itkwidgets? 

(env) MMY640:virtual-python pluto$ python --version
Python 3.8.2
(env) MMY640:virtual-python pluto$ python -m pip install itkwidgets
Collecting itkwidgets
  Using cached itkwidgets-0.26.1-py2.py3-none-any.whl (3.2 MB)
ERROR: Could not find a version that satisfies the requirement itk-meshtopolydata>=0.5.1 (from itkwidgets) (from versions: none)
ERROR: No matching distribution found for itk-meshtopolydata>=0.5.1 (from itkwidgets)

**Comment by dzenanz** [comment]
For now, we need to use Python 3.7. The final release of ITK 5.1.0 is expected next month.

**Comment by thewtex** [comment]
[Pre-release packages are available](https://pypi.org/project/itk-meshtopolydata/0.6rc1/#files). Install with:

```
python -m pip install --upgrade --pre itk-meshtopolydata
```

**Comment by ecederstrand** [comment]
Thanks! The pre-release packages allow me to use Python 3.8
