### ISSUE TITLE
Update to use ITK's new progress updater

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/ITKMeshToPolyData#24]
Fails to have all tests pass when using ITK Head (2020.03.03)

\MeshToPolyDataTestDriver.exe.manifest" failed (exit code 1120) with the following output:
itkImageToPointSetFilterTest.cxx.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl itk::ProcessObject::SetThreaderUpdateProgress(bool)" (?SetThreaderUpdateProgress@ProcessObject@itk@@MEAAX_N@Z)
itkMeshToPolyDataFilterTest.cxx.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl itk::ProcessObject::SetThreaderUpdateProgress(bool)" (?SetThreaderUpdateProgress@ProcessObject@itk@@MEAAX_N@Z)
C:\src\ITK-Release\bin\MeshToPolyDataTestDriver.exe : fatal error LNK1120: 1 unresolved externals
[8/19] Generating C:/src/ITK-Release/W...ping/Typedefs/itkPyVectorContainer.idx
ninja: build stopped: subcommand failed.

**Comment by thewtex** [comment]
@dzenanz @blowekamp please take a look at the progress updater symbol export specification.

**Comment by dzenanz** [comment]
I took a look at export specifications. A likely source of that error is outdated build tree. The new header calls for `SetThreaderUpdateProgress`, but the compiled source is old, without it.

With #25 applied, this module builds for me using [a recent ITK](https://github.com/InsightSoftwareConsortium/ITK/commit/b06c2f85ced2647eb2c214ebe72599d94008265f), which includes the `SetThreaderUpdateProgress` symbol.
