### ISSUE TITLE
New release with Mac arm64 support?

### ISSUE THREAD

**Issue by rly** [InsightSoftwareConsortium/ITKMeshToPolyData#56]
Hi, it seems that the pypi wheels on [pypi.org/project/itk-meshtopolydata/#files](https://pypi.org/project/itk-meshtopolydata/#files) do not support macs with arm64 architecture.

Personally, I've come here from itkwidgets and https://github.com/NeurodataWithoutBorders/ccf-widget/issues/30#issuecomment-1413006180. I cannot install the latest non-prerelease version of itkwidgets on my Mac M1. 

```
$ pip install -U itkwidgets==0.32.5 --verbose
Using pip 23.0 from /Users/rly/mambaforge/envs/test-ccfwidget/lib/python3.10/site-packages/pip (python 3.10)
Collecting itkwidgets==0.32.5
  Using cached itkwidgets-0.32.5-py2.py3-none-any.whl (3.4 MB)
Collecting colorcet
  Using cached colorcet-3.0.1-py2.py3-none-any.whl (1.7 MB)
ERROR: Could not find a version that satisfies the requirement itk-meshtopolydata>=0.10 (from itkwidgets) (from versions: none)
ERROR: No matching distribution found for itk-meshtopolydata>=0.10
```

Thanks!

**Comment by thewtex** [comment]
Hi @rly ,

Python packages have been uploaded for mac arm64 for 3.9, 3.10, 3.11. Please give them a try! :pray:

**Comment by rly** [comment]
Thanks! This worked.
