### ISSUE TITLE
0.10.0 MacOS arm64 wheel on pypi breaks itk install

### ISSUE THREAD

**Issue by akenmorris** [InsightSoftwareConsortium/ITKMeshToPolyData#60]
The only available package on pypi, `itk_meshtopolydata-0.10.0-cp311-cp311-macosx_11_0_arm64.whl` includes a blank `itk/__init__.py` file.  This overwrites the `itk/__init__.py` file from the `itk` package and renders it unable to be used.

Perhaps this is fixed with `0.11rc1`?  However no MacOS arm64 build is available.

**Comment by thewtex** [comment]
Hi, please use `0.11.0`.
